version: '3'

services:
  mautic:
    image: mautic/mautic:v4
    restart: always
    networks:
      - database
      - mautic
    depends_on:
      - mysql
    ports:
      - 80:80
    environment:
      - MAUTIC_DB_HOST=mysql
      - MAUTIC_DB_USER=mautic
      - MAUTIC_DB_PASSWORD=secret
      - MAUTIC_DB_NAME=mautic
      - MAUTIC_RUN_CRON_JOBS=true
    volumes:
      - ./.data/mautic:/var/www/html

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - database
    environment:
      - MYSQL_USER=mautic
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=mautic
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - ./.data/mysql:/var/lib/mysql

networks:
  database:
  mautic:
